apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: testevents-trigger
  namespace: default
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

---

# This is a very simple Knative Service that writes the input request to its log.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: default
spec:
  template:
    spec:
      containers:
      - # This corresponds to
        # https://github.com/knative/eventing-contrib/tree/master/cmd/event_display/main.go
        image: gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display
