apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: eda-sinkbinding
  namespace: default
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: eda
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
