apiVersion: sources.knative.dev/v1alpha1
kind: PingSource
metadata:
  name: ping-source
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
