# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      pip install mkdocs-material 
      pip install mkdocs-material-extensions mkdocs-macros-plugin mkdocs-exclude mkdocs-awesome-pages-plugin mkdocs-redirects # runs during prebuild
    command: mkdocs serve


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
