apiVersion: serving.knative.dev/v1alpha1
kind: Service
name: go-demo
namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/{PROJECT_ID}/helloworld-csharp