apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-java-spring
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/{username}/helloworld-java-spring
            env:
            - name: TARGET
              value: "Spring Boot Sample v1"
