apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-ruby
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/helloworld-ruby
        env:
        - name: TARGET
          value: "Ruby Sample v1"
