apiVersion: v1
kind: Secret
metadata:
  name: githubsecret
type: Opaque
data:
  # Generate a personal access token from GitHub
  # See https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
  personalAccessToken: <base64 encoded personal access token>
  # The secret specified when creating the webhook on GitHub
  # This is used to validate incoming webhook messages.
  webhookSecret: <base64 encoded webhook secret>