apiVersion: events.cloud.google.com/v1alpha1
kind: PubSub
metadata:
  name: testing-source
spec:
  topic: testing
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default
  # If running in GKE, we will ask the metadata server for the project.
  #project: MY_GCP_PROJECT
