apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
        role: master
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis
        ports:
        - containerPort: 6379
