apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-secret
type: Opaque
stringData:
  consumerKey: <YOUR OAUTH CONSUMER KEY FROM BITBUCKET>
  consumerSecret: <YOUR OAUTH CONSUMER SECRET FROM BITBUCKET>
