apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: iot-demo
  namespace: default
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

---
# This is a very simple Knative Service that writes the input request to its log.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: default
spec:
  template:
    spec:
      containers:
        image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
