apiVersion: messaging.knative.dev/v1alpha1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
  steps:
  - ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: first
  - ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: second
  - ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: third
  reply:
    kind: Service
    apiVersion: serving.knative.dev/v1beta1
    name: event-display
