apiVersion: v1
kind: Secret
metadata:
  name: google-robot-secret
  namespace: default

stringData:
  robot.json: |
    You can place the body of the Google Service Account key file
    here for use with this sample.  Be careful that each line of
    the JSON key file has been indented enough so that it remains
    a part of the "robot.json" key's value.
