apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-scala
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: "your_repository_name/helloworld-scala:0.0.1"
            imagePullPolicy: IfNotPresent
            env:
              - name: MESSAGE
                value: "Scala & Akka on Knative says hello!"
              - name: HOST
                value: "localhost"
