# MetaSources are not intended to be used directly by a user. Rather they are to help make other
# sources easy to write and maintain.
metaSources:
  - name: SinkBinding
    url: https://knative.dev/docs/eventing/samples/sinkbinding/
    status: Active Development
    support: Knative
    description: >
      SinkBinding provides a framework for injecting `K_SINK` (destination address) and
      `K_CE_OVERRIDES` (JSON cloudevents attributes) environment variables into any Kubernetes
      resource which has a `spec.template` that looks like a Pod (aka PodSpecable).
  - name: Container Source
    url: https://knative.dev/docs/eventing/migration/sinkbinding
    status: Active Development
    support: Knative
    description: >
      Given a `spec.template` with at least a container image specified, ContainerSource will keep a `Pod`
      running with the specified image(s). `K_SINK` (destination address) and `KE_CE_OVERRIDES` (JSON
      CloudEvents attributes) environment variables are injected into the running image(s). It is used by multiple
      other Sources as underlying infrastructure.
  - name: Auto Container Source
    url: https://github.com/Harwayne/auto-container-source
    status: Proof of Concept
    support: None
    description: >
      AutoContainerSource is a controller that allows the Source CRDs _without_ needing a
      controller. It notices CRDs with a specific label and starts controlling resources of that
      type. It utilizes Container Source as underlying infrastructure.
  - name: Sample Source
    url: https://github.com/knative/sample-source
    status: Active Development
    support: Knative
    description: >
      Used as reference implementation supporting
      [Writing an Event Source from Scratch tutorial](../samples/writing-receive-adapter-source).


# Sources are event sources that users can install and use directly.
sources:
  - name: Apache Camel
    url: https://github.com/knative/eventing-contrib/blob/master/camel/source/pkg/apis/sources/v1alpha1/camelsource_types.go
    status: Proof of Concept
    support: None
    description: >
      Allows to use [Apache Camel](https://github.com/apache/camel) components for pushing events into Knative.
  - name: AWS SQS
    url: https://github.com/knative/eventing-contrib/blob/master/awssqs/pkg/apis/sources/v1alpha1/aws_sqs_types.go
    status: Proof of Concept
    support: None
    description: >
      Brings [AWS Simple Queue Service](https://aws.amazon.com/sqs/) messages into Knative.
  - name: Cron Job
    url: https://knative.dev/docs/eventing/migration/ping
    status: Replaced by PingSource
    support: None
    description: >
      Deprecated, replace with [PingSource](https://knative.dev/docs/eventing/migration/ping) or a [CronJob using SinkBinding](https://knative.dev/docs/eventing/samples/sinkbinding/)
  - name: Ping
    url: https://github.com/knative/eventing/blob/master/pkg/apis/sources/v1alpha2/ping_types.go
    status: In development
    support: None
    description: >
      Uses an in-memory timer to produce events with a fixed payload on a specified cron schedule.
  - name: CloudPubSubSource
    url: https://github.com/google/knative-gcp/blob/master/docs/examples/cloudpubsubsource/README.md
    status: Active Development
    support: None
    description: >
      Brings [Cloud Pub/Sub](https://cloud.google.com/pubsub/) messages into Knative.
  - name: CloudSchedulerSource
    url: https://github.com/google/knative-gcp/blob/master/docs/examples/cloudschedulersource/README.md
    status: Active Development
    support: None
    description: >
      Create, update, and delete [Google Cloud Scheduler](https://cloud.google.com/scheduler/) Jobs. When those jobs are triggered, receive the event inside Knative.
  - name: CloudStorageSource
    url: https://github.com/google/knative-gcp/blob/master/docs/examples/cloudstoragesource/README.md
    status: Active Development
    support: None
    description: >
      Registers for events of the specified types on the specified [Google Cloud Storage](https://cloud.google.com/storage/) bucket and optional object prefix. Brings those events into Knative.
  - name: CloudAuditLogsSource
    url: https://github.com/google/knative-gcp/blob/master/docs/examples/cloudauditlogssource/README.md
    status: Active Development
    support: None
    description: >
      Registers for events of the specified types on the specified [Google Cloud Audit Logs](https://cloud.google.com/logging/docs/audit/). Brings those events into Knative.
  - name: GitHub
    url: https://github.com/knative/eventing-contrib/blob/master/github/pkg/apis/sources/v1alpha1/githubsource_types.go
    status: Proof of Concept
    support: None
    description: >
      Registers for events of the specified types on the specified GitHub organization/repository.
      Brings those events into Knative.
  - name: GitLab
    url: https://github.com/knative/eventing-contrib/blob/master/gitlab/pkg/apis/sources/v1alpha1/gitlabsource_types.go
    status: Proof of Concept
    support: None
    description: >
      Registers for events of the specified types on the specified GitLab repository. Brings those
      events into Knative.
  - name: BitBucket
    url: https://github.com/nachocano/bitbucket-source
    status: Proof of Concept
    support: None
    description: >
      Registers for events of the specified types on the specified BitBucket organization/repository.
      Brings those events into Knative.
  - name: Kubernetes
    url: https://github.com/knative/eventing/blob/master/pkg/apis/sources/v1alpha1/apiserver_types.go
    status: Active Development
    support: Knative
    description: >
      Brings Kubernetes API server events into Knative.
  - name: Apache Kafka
    url: https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/apis/sources/v1alpha1/kafka_types.go
    status: Proof of Concept
    support: None
    description: >
      Brings [Apache Kafka](https://kafka.apache.org/) messages into Knative.
  - name: Apache CouchDB
    url: https://github.com/knative/eventing-contrib/tree/{{< branch >}}/couchdb
    status:  Active Development
    support: None
    description: >
      Brings [Apache CouchDB](https://couchdb.apache.org/) messages into Knative.
  - name: VMware
    url: https://github.com/vmware-tanzu/sources-for-knative/tree/{{< branch >}}/pkg/apis/source/v1alpha1/vspheresource_types.go
    status:  Active Development
    support: None
    description: >
      Brings [vSphere](https://www.vmware.com/products/vsphere.html) events into Knative.

# These are containers intended to be used with ContainerSource, but are not CRDs.
containers:
  - name: Heartbeats
    url: https://github.com/knative/eventing-contrib/tree/{{< branch >}}/cmd/heartbeats
    status: Proof of Concept
    support: None
    description: >
      Uses an in-memory timer to produce events at the specified interval.
  - name: WebSocket
    url: https://github.com/knative/eventing-contrib/tree/{{< branch >}}/cmd/websocketsource
    status: Active Development
    support: None
    description: >
      Opens a WebSocket to the specified source and packages each received message as a Knative
      event.
  - name: K8s
    url: https://github.com/Harwayne/auto-container-source/tree/master/k8s-event-source
    status: Proof of Concept
    support: None
    description: >
      Brings Kubernetes cluster events into Knative. Uses AutoContainerSource for underlying
      infrastructure.
  - name: Heartbeat
    url: https://github.com/Harwayne/auto-container-source/tree/master/heartbeat-source
    status: Proof of Concept
    support: None
    description: >
      Uses an in-memory timer to produce events as the specified interval. Uses AutoContainerSource
      for underlying infrastructure.
  - name: AWS CodeCommit
    url: https://github.com/triggermesh/aws-event-sources/blob/master/cmd/awscodecommitsource/README.md
    status: Supported
    support: TriggerMesh
    description: >
      Registers for events of the specified types on the specified AWS CodeCommit repository. Brings those events into Knative.
  - name: AWS Cognito
    url: https://github.com/triggermesh/aws-event-sources/blob/master/cmd/awscognitosource/README.md
    status: Supported
    support: TriggerMesh
    description: >
      Registers for AWS Cognito events. Brings those events into Knative.
  - name: AWS DynamoDB
    url: https://github.com/triggermesh/aws-event-sources/blob/master/cmd/awsdynamodbsource/README.md
    status: Supported
    support: TriggerMesh
    description: >
      Registers for events of on the specified AWS DynamoDB table. Brings those events into Knative.
  - name: AWS Kinesis
    url: https://github.com/triggermesh/aws-event-sources/tree/master/cmd/awskinesissource/README.md
    status: Supported
    support: TriggerMesh
    description: >
      Registers for events on the specified AWS Kinesis stream. Brings those events into Knative.
  - name: AWS SQS
    url: https://github.com/triggermesh/aws-event-sources/tree/master/cmd/awssqssource/README.md
    status: Supported
    support: TriggerMesh
    description: >
      Registers for events of the specified AWS SQS queue. Brings those events into Knative.
  - name: AWS SNS
    url: https://github.com/triggermesh/aws-event-sources/tree/master/cmd/awssnssource
    status: Supported
    support: TriggerMesh
    description: >
      Registers for events of the specified AWS SNS endpoint. Brings those events into Knative.
  - name: FTP / SFTP
    url: https://github.com/vaikas-google/ftp
    status: Proof of concept
    support: None
    description: >
      Watches for files being uploaded into a FTP/SFTP and generates events for those.

# These are intended to be used with SinkBinding, but are not CRDs.
sinkBindings:
  - name: Konnek
    url: https://konnek.github.io/docs/#/
    status: Active Development
    support: None
    description: >
      Retrieves events from cloud platforms (like AWS and GCP) and transforms them into CloudEvents for consumption in Knative.
