apiVersion: flows.knative.dev/v1beta1
kind: Parallel
metadata:
  name: me-odd-even-parallel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  branches:
  - filter:
      uri: "http://me-even-odd-switcher.default.svc.cluster.local/0"
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: me-even-transformer
  - filter:
      uri: "http://me-even-odd-switcher.default.svc.cluster.local/1"
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: me-odd-transformer
  reply:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: me-event-display
