apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-apl
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/helloworld-apl:0.0.1
            env:
            - name: TARGET
              value: "APL Sample v1"
            - name: FUNC_HANDLER
              value: "helloWorld"
