apiVersion: v1
kind: Service
metadata:
  name: otel-prom
  namespace: metrics
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  ports:
  - name: prom-export
    port: 8889
    targetPort: 8889
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: opentelemetry-collector
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: metrics
  labels:
    source: otel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  endpoints:
  - port: prom-export
    path: "/metrics"
    honorTimestamps: true
    honorLabels: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: metrics
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: metrics
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      source: otel
  resources:
    requests:
      memory: 200Mi
  enableAdminAPI: true
