apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-vertx
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/slinkydeveloper/cloudevents-vertx-sample
