name: Build Images

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
    - "code-samples/serving/hello-world/helloworld-go/**"
    - "code-samples/eventing/bookstore-sample-app/**"
    - "docs/serving/autoscaling/autoscale-go/**"
    - "hack/docker/**"
    - ".github/workflows/knative-docs-image.yaml"
    - "requirements.txt"

jobs:
  build-and-push-image:
    name: Build Knative Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mkdocs image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./hack/docker/Dockerfile
          tags: ghcr.io/knative/knative-docs:latest

      - name: Build helloworld-go image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          context: ./code-samples/serving/hello-world/helloworld-go
          tags: ghcr.io/knative/helloworld-go:latest

      - name: Build autoscale-go image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          context: ./docs/serving/autoscaling/autoscale-go
          tags: ghcr.io/knative/autoscale-go:latest

      - name: Build sample-app's frontend image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: ./code-samples/eventing/bookstore-sample-app/solution/frontend
          tags: ghcr.io/knative/bookstore-frontend:latest

      - name: Build sample-app's node-server image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: ./code-samples/eventing/bookstore-sample-app/solution/node-server
          tags: ghcr.io/knative/node-server:latest
