apiVersion: messaging.knative.dev/v1alpha1
kind: Choice
metadata:
  name: me-odd-even-choice
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
  cases:
  - filter:
      uri: "http://me-even-odd-switcher.default.svc.cluster.local/0"
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: me-even-transformer
  - filter:
      uri: "http://me-even-odd-switcher.default.svc.cluster.local/1"
    subscriber:
      ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: me-odd-transformer
  reply:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: me-event-display